### ISSUE TITLE
Alphabet Invasion Game - Add button to increase the speed of letters

### ISSUE THREAD

**Issue by marlonchosky** [adamlubek/rxjs-examples#1]
Hi. I would like to implement a button in the game. Clicking on this button would accelerate the speed of the letters, but the letters already produced would not be lost.

Can you help me with this pls

**Comment by adamlubek** [comment]
hey! I'm really sorry about the delay! I'm bit busy at the moment but maybe will carve out some time to take a look into this over next 2 weeks :)

**Comment by marlonchosky** [comment]
Hi!!! Please don't forget it :(

**Comment by adamlubek** [comment]
Hey, really sorry but I'm super busy with work :( but maybe will carve out some time to look at it this or next weekend!

**Comment by adamlubek** [comment]
hey @marlonedu , how about this: https://stackblitz.com/edit/rxjs-alphabet-invasion-ver2

**Comment by adamlubek** [comment]
I'm closing this, let me know if you still need something else :)
